user_index:
    path:     /
    defaults: { _controller: "LgmBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "LgmBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "LgmBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "LgmBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "LgmBundle:User:delete" }
    methods:  DELETE
    
user_ficheChercheurPDF:
    path:     /{id}/ficheChercheurPDF
    defaults: { _controller: "LgmBundle:User:ficheChercheurPDF" }
    methods:  [GET, POST]

user_ficheDoctorant:
    path:     /{id}/ficheDoctorant
    defaults: { _controller: "LgmBundle:User:ficheDoctorant" }
    methods:  [GET, POST]